### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by gwendall** [XervoIO/atom-modulus#4]
I get the following error when trying to install the package.

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.3
**Thrown From**: [modulus](https://github.com/onmodulus/atom-modulus) package, v0.0.3
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/gwendallesnault/.atom/packages/modulus/lib/modulus-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/gwendallesnault/.atom/packages/modulus/lib/modulus-view.coffee:4:199)
  at /Users/gwendallesnault/.atom/packages/modulus/lib/modulus-view.coffee:28:3
  at Object.<anonymous> (/Users/gwendallesnault/.atom/packages/modulus/lib/modulus-view.coffee:201:5)
  at Object.<anonymous> (/Users/gwendallesnault/.atom/packages/modulus/lib/modulus-view.coffee:22:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/gwendallesnault/.atom/packages/modulus/lib/modulus.coffee:22:15)
  at Object.<anonymous> (/Users/gwendallesnault/.atom/packages/modulus/lib/modulus.coffee:22:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/src/package.js:759:34)
  at Package.module.exports.Package.activateConfig (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/src/package.js:261:14)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:150:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:187:12)
  at /Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:232:24
  at Emitter.module.exports.Emitter.emit (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:587:27)
  at /Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:378:26
  at exit (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/_APPS/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -7:04.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  9x -6:39.8.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -6:38.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:33.8.0 core:cut (atom-text-editor.editor.mini.is-focused)
     -6:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:31.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -4:27.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:26.4.0 core:save (atom-text-editor.editor.is-focused)
     -4:18.5.0 core:move-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:12.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:08.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:08.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:07.9.0 core:select-down (atom-text-editor.editor.is-focused)
  2x -4:07.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:06.8.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:50.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.4
file-icons, v1.5.7
language-jade, v0.4.0
linter, v1.3.2
linter-csslint, v1.0.5
linter-htmlhint, v0.0.17
linter-jshint, v1.1.4
meteor-api, v2.19.0
minimap, v4.12.2
monokai, v0.14.0
pigments, v0.9.3

# Dev
No dev packages
```

**Comment by tzmanics** [comment]
Hi @gwendall sorry for the big delay in response. We aren't currently maintaining this repo so I'm going to close this issue for now, BUT if it's something you're still dealing with please feel free to re-open the issue! Once we figure out the next steps for 'atom-modulus` we'll update the repo.
