### ISSUE TITLE
Failed to load the modulus package

### ISSUE THREAD

**Issue by lambertpark** [XervoIO/atom-modulus#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [modulus](https://github.com/onmodulus/atom-modulus) package, v0.0.3
### Stack Trace

Failed to load the modulus package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/lambert/.atom/packages/modulus/lib/modulus-view.coffee:22:1)
  at /Users/lambert/.atom/packages/modulus/lib/modulus-view.coffee:28:3
  at Object.<anonymous> (/Users/lambert/.atom/packages/modulus/lib/modulus-view.coffee:201:5)
  at Object.<anonymous> (/Users/lambert/.atom/packages/modulus/lib/modulus-view.coffee:22:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/lambert/.atom/packages/modulus/lib/modulus.coffee:22:15)
  at Object.<anonymous> (/Users/lambert/.atom/packages/modulus/lib/modulus.coffee:22:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:725:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:176:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:396:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:363:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:25)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
coffee-compile, v0.19.2
color-picker, v2.0.13
emmet, v2.3.13
file-icons, v1.6.11
jsonlint, v1.1.2
minimap, v4.15.0
modulus, v0.0.3
project-manager, v2.6.5
run-in-terminal, v0.4.2
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by lambertpark** [comment]
.

**Comment by tzmanics** [comment]
Hi @LambertPark sorry for the big delay in response. We aren't currently maintaining this repo so I'm going to close this issue for now, BUT if it's something you're still dealing with please feel free to re-open the issue! Once we figure out the next steps for 'atom-modulus` we'll update the repo.
